#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Pedro Perez

# Short bio or description (displayed in the header)
description: Las redes WiFi abiertas son como un soplo de aire fresco para el usuario que se ha quedado
sin datos en su smartphone, o para el que necesita conectar su ordenador para enviar un trabajo de última
hora. Ahora hay WiFi gratis por tierra, mar y aire, así que también es un alivio para el que va a realizar
un viaje largo a bordo de un AVE, un autobús o un avión, ya que en estos tiempos los dispositivos móviles son
un complemento tan necesario para el viajero como la maleta.Sin embargo, conectarse a una WiFi abierta no siempre
es seguro. El caso más peligroso es el de las redes extrañas. Según cuenta EL MUNDO el director técnico de
PandaLabs en Panda Security, Luis Corrons, "no sabemos de dónde procede ni quién maneja esta conexión.
Lo mejor es no probarla", advierte.El motivo es simple, detrás de esta WiFi gratuita puede estar cualquier persona,
incluso un ciberdelincuente. "Así, sería muy fácil que intentase infectar tu dispositivo con malware o redirigiese
tu tráfico a páginas fraudulentas para robar tus datos", explica Corróns. Y es que esta es una estrategia de phishing
muy habitual, en la que si el usuario quiere entrar en su correo electrónico, por ejemplo, el estafador le redirige
a una página que se parece mucho, pero que no es la original, con el fin de poder hacerse con su credenciales para
vender sus datos en el mercado negro o para cometer otro tipo de fraudes por email.
La seguridad de tus datos depende de tíEn el caso de las redes conocidas, como las que ofrecen bibliotecas,
autobuses, trenes, aeropuertos, hoteles y otros servicios, los peligros son otros, pues en este caso sabemos
que el gestor de la red WiFi es seguro. Sin embargo, ahora dependerá de nosotros que nuestros datos se mantengan
a salvo de manos ajenas, pues todo el tráfico que se realice dentro de estas redes será visible para sniffers,
que no son otra cosa que un programa informático que registra la información que envían los dispositivos.
Según cuenta Corróns, mientras naveguemos en páginas seguras (https) o utilicemos aplicaciones conocidas,
nuestros datos no corren peligro. En este caso, hay que tener especial cuidado con las contraseñas, ya que,
si estamos en una red no segura (http), un sniffer podría detectar nuestro tráfico sin cifrar. "Si accedemos
a una suscripción o a un foro con el mismo usuario y contraseña que usamos para todo, un ciberdelincuente podría
entrar en nuestras cuentas de Facebook, correo electrónico, Twitter, etc". De esta forma, podría extorsionar
a nuestros contactos con el fin de conseguir dinero. "Un fraude muy conocido es que contacte con nuestros
amigos de Facebook y les diga que estamos en el extranjero y que nos han robado, por lo que necesitamos
que nos ingresen una gran cantidad de dinero para volver", explica Corróns. Es por esto que es muy importante
no utilizar las mismas credenciales para todas nuestras cuentas.Por su parte, el director de ciberseguridad
de Atos Iberia, Javier Zapata, advierte que una red pública es como entrar en un parque, por lo que como usuarios
"debemos adoptar una actitud prudente y no realizar acciones que no realizaríamos delante de otras personas,
nunca sabemos quién puede estar viendo nuestro tráfico", advierte. Así, este experto recomienda "no acceder a
banca online ni a lugares de la administración pública, como puede ser Hacienda o Sanidad", así como que nos
abstengamos de enviar archivos a través de páginas web no seguras "porque sería como compartirlas con todo el mundo".
Otros problemas llegan la mayor parte de las veces a través de agujeros de seguridad ya conocidos, por lo que también
es necesario mantener siempre todo actualizado, ya que los parches llegan con las actualizaciones.Además,
según advierte Corróns, "debemos asegurarnos de que entramos en la red correcta, es muy común que los cibercriminales
creen zonas WiFi con nombres parecidos a los de la red segura para hacer picar a los usuarios".

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: 
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url:

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
